services:
  avito-parser:
    build: .
    container_name: avito-parser-app
    # Монтируем базу данных и логи, чтобы они не терялись при перезапуске контейнера
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
      - ./trash:/app/trash
    # Подключаем .env файл для конфигурации
    env_file:
      - .env

  avito-parser-bot:
    build: .
    container_name: avito-parser-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
      - ./trash:/app/trash
    command: python telegram_bot/bot.py